export const headerLinks = [
  {
    title:'发现音乐',
    link:'/',
    id:1
  },
  {
    title:'我的音乐',
    link:'/mine',
    id:2
  },
  {
    title:'朋友',
    link:'/friend',
    id:3
  },
  {
    title:'商城',
    link:'https://music.163.com/store/product',
    id:4
  },
  {
    title:'音乐人',
    link:'https://music.163.com/#/login?targetUrl=http%3A%2F%2Fmusic.163.com%2Fmusician%2Fartist',
    id:5
  },
  {
    title:'下载客户端',
    link:'/download',
    id:6
  }
]